# Generated by Django 2.2.4 on 2019-09-14 09:07

from django.db import migrations, models
import django.utils.timezone
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='First name')),
                ('surname', models.CharField(max_length=255, verbose_name='Last name')),
                ('email_verified', models.BooleanField(default=False)),
                ('verify_key', models.CharField(blank=True, max_length=127, null=True)),
                ('verify_expiration', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'PARTICIPANT'), (1, 'ORGANISER')], default=0)),
                ('picture', versatileimagefield.fields.VersatileImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
