# Generated by Django 2.2.4 on 2019-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
                ('language', models.CharField(default='en', max_length=2)),
                ('tags', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
