# Generated by Django 2.2.4 on 2019-09-14 20:01

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190914_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
