# Generated by Django 2.2.4 on 2019-09-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190914_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
